"""
Django settings for celery_playground project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-5#x3o4r(ic@rijoaesd3j$ssal7ykr@mhut!9!a9lraw8rg0!u'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'demo',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'celery_playground.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'celery_playground.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ═══════════════════════════════════════════════════════════════════════
# CELERY CONFIGURATION - Production Ready
# ═══════════════════════════════════════════════════════════════════════

# Broker & Backend
CELERY_BROKER_URL = "redis://localhost:6380/0"
CELERY_RESULT_BACKEND = "redis://localhost:6380/1"

# Serialization Security (Golden Rule #7)
# NEVER use pickle - it's a critical RCE vulnerability
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_ACCEPT_CONTENT = ["json"]

# Timezone
CELERY_TIMEZONE = "UTC"
CELERY_ENABLE_UTC = True

# Task Reliability (Golden Rules #2)
CELERY_TASK_ACKS_LATE = True  # ACK only after successful execution
CELERY_TASK_REJECT_ON_WORKER_LOST = True  # Re-queue on SIGKILL
CELERY_TASK_TRACK_STARTED = True  # Enable STARTED state

# Worker Performance (Golden Rule #3)
CELERYD_PREFETCH_MULTIPLIER = 1  # Critical: prevents invisible task starvation

# Result TTL - prevent memory leak
CELERY_RESULT_EXPIRES = 3600  # 1 hour

# Redis Transport Options (Golden Rule #4)
CELERY_BROKER_TRANSPORT_OPTIONS = {
    'visibility_timeout': 86400,  # 24 hours - must be > longest task
    'max_connections': 20,
    'socket_connect_timeout': 5,
    'socket_timeout': 10,
    'retry_on_timeout': True,
}

# Task Time Limits (Golden Rule #6)
# Set per-task in production; these are defaults
CELERYD_TASK_SOFT_TIME_LIMIT = 300  # 5 min - raises exception
CELERYD_TASK_TIME_LIMIT = 360  # 6 min - SIGKILL

# Worker Recycling - prevent memory leaks
CELERYD_MAX_TASKS_PER_CHILD = 200  # Recycle worker after N tasks
CELERYD_MAX_MEMORY_PER_CHILD = 400000  # 400MB hard limit (in KB)
